spring.application.name=servicio_eureka
server.port=8761

# Todos los microservicios al levantarse se registran en Eureka
# Tenemenos que desactivar que el propio servidor se registre a si mismo
# Le decimos "Tu no eres un cliente Eureka"
eureka.client.register-with-eureka=false

# Asi que no te registres
eureka.client.fetch-registry=false
